Add calculator
JuliCarracedo/math-magicians pull request #2
Opened 2021-09-14 21:48 UTC by JuliCarracedo

This PR by @JuliCarracedo introduces the style and form of the math magicians' calculator.

2021-09-14 22:13 UTC, Emmyn5600 requested changes
## STATUS: CHANGES REQUESTED :recycle:

Hi, @JuliCarracedo 

Great work on implementing the project requirements, however there are some issues to be solved before you get approved but you are almost there:muscle:. 
   
 - The repo looks professional.:heavy_check_mark:
- There are no linter errors:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:
-  Git/GitHub flow best practices have been followed.:heavy_check_mark:
- Great design matching with the given design:heavy_check_mark:

Changes required :writing_hand: 
  
   - Please check the comment under the review.

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2021-09-14 22:13 UTC, Emmyn5600 commented on src/Calculator.js
> +export default Calculator;
- [ ] There should be a Calculator.js file inside the components directory.
- [ ] The Calculator.js component should be class-based
![storage5](https://user-images.githubusercontent.com/55635977/133340584-305a85e5-337a-441b-a9eb-4ddabcef0871.png)

- [ ] The App.js component should be class-based.
- [ ] The App.js(main component) should have the imported the Calculator.js component 

!![storage1](https://user-images.githubusercontent.com/55635977/133340895-86180f82-aa1b-4c3c-8d0f-01723d582d5e.png)

2021-09-14 23:51 UTC, oxenprogrammer requested changes
Hi @JuliCarracedo , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet. :muscle:


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Consider the optional changes nice to have features and only work on them when you have satisfied the required changes_

- [ ] Your design is elegant but let us try to follow the given design as close as possible. Converting UX/UI design into code is definitely one of the roles you will play as a front-end developer.
**Your Design**
![cal](https://user-images.githubusercontent.com/7220167/133348623-f4753a6f-72f2-4acb-bed3-3b3015dcc7a5.png)

**Expected Design**
![calculator](https://user-images.githubusercontent.com/7220167/133348653-6bc01c59-7087-4c83-8db5-1953d4436edc.png)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-09-14 23:51 UTC, oxenprogrammer commented on components/Calculator.js
> +// class Field extends React.Components {
**Changes Required**
- [ ] Let us try not to commit commented out code to our repo. It makes it look unprofessional. You can use `git history` to track your changelog. Let us try to remove these and delete this directory `src/components` as a whole.

2021-09-15 00:28 UTC, oxenprogrammer approved these changes
Hi @JuliCarracedo , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-16 20:17 UTC, merged